// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import BootstrapSwitchController from "./bootstrap_switch_controller"
import HelloController from "./hello_controller"
import DateRangePickerController from "./daterangepicker_controller"
import Select2 from "./select2_controller"

application.register("hello", HelloController)
application.register("bootstrap-switch", BootstrapSwitchController)
application.register("daterangepicker", DateRangePickerController)
application.register("select2", Select2)
